[project]
name = "assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Stephen", email = "stearsail@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "agno>=3.0.6",
    "fastmcp>=4.0.3",
    "mcp>=2.1.1",
    "python-dotenv>=1.2.3",
    "questionary>=2.1.1",
]

[project.scripts]
assistant = "assistant.cli:main"

[build-system]
requires = ["uv_build>=0.11.26,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.6",
]
